- hosts: localhost
  become: true
  pre_tasks:
    - include_vars: defaults.yml
    - include_vars: secrets_env.yml
    - include_vars: secrets_ssh.yml
    - include_vars: secrets_aws.yml
    - include_vars: secrets_snowsql.yml
    - include_vars: secrets_metaflow.yml
    - include_vars: secrets_aws_okta_login_config.yml
    - include_vars: secrets_maven_settings.yml
  tasks:
    - include_tasks: tasks/upgrade.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/environment_variables.yml
    - include_tasks: tasks/programming.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/fish.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/guake.yml
    - include_tasks: tasks/personal.yml
    - include_tasks: tasks/browsers.yml
    - include_tasks: tasks/turner.yml
