- name: add docker group
  group:
    name: docker

- name: add user to docker group
  user:
    name: "{{ user }}"
    append: yes
    groups:
     - docker

- name: Install docker applications
  apt:
    pkg:
    - containerd
    - docker.io
    - docker-registry
    - docker-compose

- name: Install Kubernetes
  block:
    - name: download apt key
      get_url:
        url: https://dl.k8s.io/apt/doc/apt-key.gpg
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        force: true

    - name: add apt key
      apt_key:
        file: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: apt source
      apt_repository:
        filename: kubernetes
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        update_cache: true

- name: Install Kubectl
  block:
    - name: download kubectl (downgraded)
      get_url:
        url: https://dl.k8s.io/release/v1.23.17/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        force: true
        mode: "755"
