- name: add docker group
  group:
    name: docker

- name: add user to docker group
  user:
    name: "{{ user }}"
    append: yes
    groups:
     - docker

- name: Install docker applications
  apt:
    pkg:
    - containerd
    - docker.io
    - docker-registry
    - docker-compose

- name: Install Kubectl
  block:
    - name: download kubectl (downgraded)
      get_url:
        url: https://dl.k8s.io/release/v1.23.17/bin/linux/arm64/kubectl
        dest: /usr/local/bin/kubectl
        force: true
        mode: "755"
