- name: Prepare Kubernetes install
  apt_key:
    file: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"

- name: add docker group
  group:
    name: docker

- name: add user to docker group
  user:
    name: "{{ user }}"
    append: yes
    groups:
     - docker

- name: Install docker applications
  apt:
    pkg:
    - docker.io
    - docker-registry
    - docker-compose
    - apt-transport-https
    - kubectl

