- name: Install VMWare utilities
  apt:
    pkg:
    - open-vm-tools-desktop

- name: Install version control systems
  apt:
    pkg:
    - git
    - mercurial

- name: Install editor utilities
  apt:
    pkg:
    - vim-gtk3
    state: latest

- name: Install latest neovim
  block:
    - name: Create neovim directory
      file:
        path: /usr/local/neovim
        state: directory
        mode: "775"

    - name: Install neovim
      unarchive:
        src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: /usr/local/neovim
        remote_src: true
        mode: "775"

- name: Install system utilities (apt)
  apt:
    pkg:
    - ack
    - fish
    - gpg
    - graphviz
    - htop
    - jq
    - libsecret-tools
    - tmux
    - unzip
    - curl
    - wget
    - xclip
    - pandoc
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - gdebi
    - gdebi-core

- name: Install system utilities (golang)
  block:
    - name: Install grpcurl
      script:
        cmd: '/usr/bin/go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest'

- name: Install shared packages
  apt:
    pkg:
    - libatlas-base-dev

- name: Install DevOps applications
  apt:
    pkg:
    - mc

- name: Install programs
  apt:
    pkg:
    - chromium-browser
    - gimp

- name: Install Dropbox
  apt:
    deb: https://linux.dropbox.com/ubuntu/pool/main/dropbox_2020.03.04_amd64.deb

- name: Remove unused pre-installed packages
  apt:
    name:
      - rhythmbox
      - firefox
    state: absent

- name: Remove absent packages
  apt:
    purge: yes

- name: Install protobuf utilities for Go
  block:
    - name: Install protoc-gen-go
      script:
        cmd: '/usr/bin/go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28'
    - name: Install protoc-gen-go-grpc
      script:
        cmd: '/usr/bin/go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2'

- name: Install GitHub CLI
  block:
    - name: download apt key
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
        force: true

    - name: add apt key
      apt_key:
        file: /etc/apt/keyrings/githubcli-archive-keyring.gpg
        state: present

    - name: apt source
      apt_repository:
        filename: kubernetes
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
        update_cache: true

    - name: install gh
      apt:
        pkg:
          - gh

- name: Install yq
  block:
    - name: Install yq
      unarchive:
        src: https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64.tar.gz
        dest: /usr/local/yq
        remote_src: true
        mode: "775"
