- name: Install VMWare utilities
  apt:
    pkg:
    - open-vm-tools-desktop

- name: Install version control systems
  apt:
    pkg:
    - git
    - mercurial

- name: Install editor utilities
  apt:
    pkg:
    - vim-gtk3
    state: latest

- name: Install latest neovim
  block:
    - name: Create neovim directory
      file:
        path: /usr/local/neovim
        state: directory
        mode: "775"

    - name: Install neovim
      unarchive:
        src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: /usr/local/neovim
        remote_src: true
        mode: "775"

- name: Install system utilities (apt)
  apt:
    pkg:
    - ack
    - fish
    - gpg
    - graphviz
    - htop
    - jq
    - yq
    - libsecret-tools
    - tmux
    - unzip
    - curl
    - wget
    - xclip
    - pandoc
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - gdebi
    - gdebi-core
    - gh

- name: Install system utilities (golang)
  block:
    - name: Install grpcurl
      script:
        cmd: '/usr/bin/go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest'

- name: Install shared packages
  apt:
    pkg:
    - libatlas-base-dev

- name: Install DevOps applications
  apt:
    pkg:
    - mc

- name: Install programs
  apt:
    pkg:
    - chromium-browser
    - gimp

- name: Remove unused pre-installed packages
  apt:
    name:
      - rhythmbox
      - firefox
    state: absent

- name: Remove absent packages
  apt:
    purge: yes

- name: Install protobuf utilities for Go
  block:
    - name: Install protoc-gen-go
      script:
        cmd: '/usr/bin/go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.0'
    - name: Install protoc-gen-go-grpc
      script:
        cmd: '/usr/bin/go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0'
