- name: Install Programming Languages
  apt:
    pkg:
    - gcc
    - clang
    - gdb
    - radare2
    - nasm
    - golang
    - ghc
    - nodejs
    - npm
    - python3
    - make

- name: Install python based utils
  apt:
    pkg:
    - python3-pip
    - python3-gpg
    - python3-wheel
    - python-wheel-common
    - python-is-python3

- name: Install python packages
  pip:
    name:
    - virtualenv==20.0.30
    - setuptools==49.4.0
    - torch==1.6.0
    - tensorflow==2.3.0
    - scikit-learn==0.23.2
    - pandas==1.1.0
    - numpy==1.19.1
    - matplotlib==3.3.1
    - scipy==1.5.2
    - flake8==3.8.3
    - metaflow==2.2.5
    - jupyter==1.0.0
    - jupyterlab==2.2.9
    - gimme-aws-creds==2.4.1

- name: Install headers
  apt:
    pkg:
    - libxext-dev
    - libopenal-dev
    - libqt5webkit5
    - libxi-dev
    - libxinerama-dev
    - libxcursor-dev
    - xorg-dev

- name: Add vulkan apt key
  ansible.builtin.apt_key:
    url: http://packages.lunarg.com/lunarg-signing-key-pub.asc
    state: present

- name: Download vulkan apt sources list
  get_url:
    url: http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
    dest: /etc/apt/sources.list.d/lunarg-vulkan-focal.list
    mode: '755'

- name: Install vukan-sdk
  apt:
    update_cache: yes
    pkg:
    - vulkan-sdk

# - name: Download miniconda installer
#   get_url:
#     url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
#     dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
#     mode: '755'
# 
# - name: Install miniconda
#   command: "bash /tmp/Miniconda3-latest-Linux-x86_64.sh -p {{home}}/miniconda3 -b -u -t"
# 
# - name: ensure miniconda3 directory has the correct permissions
#   file:
#     path: "{{ home }}/miniconda3"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: "774"
#     recurse: yes
# 
# - name: Configure miniconda to use fish shell
#   command: '{{home}}/miniconda3/bin/conda init fish'
