- name: copy ssh config
  copy:
    dest: "{{ home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "600"
    content: |
      Host *
        AddKeysToAgent yes
        IdentityFile ~/.ssh/id_rsa

- name: install tfenv version
  shell:
    cmd: '{{ home }}/.tfenv/bin/tfenv install 0.12.24'

- name: configure okta config
  copy:
    dest: "{{ home }}/.okta_aws_login_config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "700"
    content: '{{ aws_okta_login_config.file_contents }}'

- name: Install awscli (v1)
  apt:
    pkg:
    - awscli

- name: Install packages for developer-tools
  apt:
    pkg:
    - fzf
    - pipx

- name: Install aws-sso-util for developer-tools
  become_user: "{{ user }}"
  script:
    cmd: "/usr/bin/pipx install aws-sso-util"

- name: Clone developer-tools
  become_user: "{{ user }}"
  git:
    repo: 'git@github.com:wbd-streaming/developer-tools.git'
    key_file: "{{ home }}/.ssh/id_rsa"
    accept_hostkey: yes
    dest: "{{ home }}/developer-tools"
    clone: yes
    update: yes

- name: Run developer-tools setup-aws-sso.sh
  become_user: "{{ user }}"
  become: yes
  environment:
    PATH: "{{ home }}/.local/bin:/usr/local/bin:/usr/bin"
  shell:
    cmd: "/bin/bash {{ home }}/developer-tools/scripts/setup-aws-sso.sh"
